# Generated by Django 3.2.16 on 2023-10-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow_user_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ('id',), 'verbose_name': 'пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
