# Generated by Django 3.2.16 on 2023-10-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20231031_2012'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_following_prevent_self_follow',
        ),
    ]
